# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options


class TestVericoda2():
    def setup_method(self, method):
        # self.driver = webdriver.Chrome()

        self.options = Options()
        self.options.headless = True
        self.options.add_experimental_option("excludeSwitches", ["enable-logging"])
        self.options.binary_location = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
        self.s = Service(r"C:\Users\mvintee\project_for_selenium\chromedriver.exe")
        self.driver = webdriver.Chrome(service=self.s)
        self.actions = ActionChains(self.driver)
        self.vars = {}


    def teardown_method(self, method):
        self.driver.quit()

    def test_form1(self):
        # Test name: vericoda2
        # Step # | name | target | value
        # 1 | open | https://qa.vericuda.net/account/login |
        self.driver.implicitly_wait(500)
        self.t = time.time()
        # self.driver.set_page_load_timeout(500)
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.get("https://qa.vericuda.net/account/login")
        # time.sleep(5)
        self.driver.set_page_load_timeout(400)
        print('Time consuming:', time.time() - self.t)

        # 2 | setWindowSize | 1050x664 |
        # self.driver.set_window_size(1050, 664)
        self.driver.maximize_window()
        # 3 | click | id=Username |
        self.driver.find_element(By.ID, "Username").click()
        time.sleep(10)
        # 4 | type | id=Username | shiva06051981@gmail.com
        self.driver.find_element(By.ID, "Username").send_keys("shiva06051981@gmail.com")
        # 5 | click | id=Password |
        self.driver.find_element(By.ID, "Password").click()
        time.sleep(5)
        # 6 | type | id=Password | 1
        self.driver.find_element(By.ID, "Password").send_keys("1")
        # 7 | click | css=.btn:nth-child(3) |
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/button").click()
        time.sleep(50)
        self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
        time.sleep(5)
        # self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[21]/td[7]/a[1]/i").click()
        # time.sleep(10)
        # self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
        # time.sleep(10)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div[1]/div[1]/div/button[2]").click()
        time.sleep(10)
        self.driver.find_element(By.ID, "name").send_keys("Automation of Vericuda")
        time.sleep(5)
        self.driver.find_element(By.ID, "FormType").send_keys("Form")
        time.sleep(5)
        self.driver.find_element(By.ID, "Description").send_keys("Automation testing")
        time.sleep(5)

        self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[1]/div[1]/a[2]/div").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[1]/ul/li[4]/button").click()
        time.sleep(5)


        self.driver.find_element(By.XPATH, "//*[@id='loading-example']/div[1]/i[1]").click()
        time.sleep(5)

        self.driver.find_element(By.XPATH, "//*[@id='loading-example']/div[2]/div/div/div[1]/div[1]/input").send_keys("Name")
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='ControlType']").send_keys("Text Area")
        time.sleep(5)
        # self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[1]/ul/li[4]/button").click()
        # time.sleep(5)
        # self.driver.find_element(By.XPATH,"//*[@id='loading-example']/div[1]/i[1]").click()
        # time.sleep(5)
        # self.driver.find_element(By.XPATH, "//*[@id='loading-example']/div[2]/div/div/div[1]/div[1]/input").send_keys("Address")
        # time.sleep(5)
        # self.driver.find_element(By.XPATH, "//*[@id='ControlType']").send_keys("Text Area")
        # time.sleep(5)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
        time.sleep(20)

    # def test_form(self):
    #     # Test name: vericoda2
    #     # Step # | name | target | value
    #     # 1 | open | https://qa.vericuda.net/account/login |
    #     self.driver.implicitly_wait(500)
    #     self.t = time.time()
    #     # self.driver.set_page_load_timeout(500)
    #     self.driver.get("chrome://settings/")
    #     self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
    #     self.driver.get("https://qa.vericuda.net/account/login")
    #     # time.sleep(5)
    #     self.driver.set_page_load_timeout(400)
    #     print('Time consuming:', time.time() - self.t)
    #
    #     # 2 | setWindowSize | 1050x664 |
    #     # self.driver.set_window_size(1050, 664)
    #     self.driver.maximize_window()
    #     # 3 | click | id=Username |
    #     self.driver.find_element(By.ID, "Username").click()
    #     time.sleep(10)
    #     # 4 | type | id=Username | shiva06051981@gmail.com
    #     self.driver.find_element(By.ID, "Username").send_keys("shiva06051981@gmail.com")
    #     # 5 | click | id=Password |
    #     self.driver.find_element(By.ID, "Password").click()
    #     time.sleep(5)
    #     # 6 | type | id=Password | 1
    #     self.driver.find_element(By.ID, "Password").send_keys("1")
    #     # 7 | click | css=.btn:nth-child(3) |
    #     self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/button").click()
    #     time.sleep(50)
    #     self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
    #     time.sleep(5)
    #     # self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[21]/td[7]/a[1]/i").click()
    #     # time.sleep(10)
    #     # self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
    #     # time.sleep(10)
    #     self.driver.find_element(By.XPATH, "/html/body/app/div/main/div[1]/div[1]/div/button[2]").click()
    #     time.sleep(10)
    #     self.driver.find_element(By.ID, "name").send_keys("Automation of Vericuda")
    #     time.sleep(5)
    #     self.driver.find_element(By.ID, "FormType").send_keys("Form")
    #     time.sleep(5)
    #     self.driver.find_element(By.ID, "Description").send_keys("Automation testing")
    #     time.sleep(5)
    #
    #     self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[1]/div[1]/a[2]/div").click()
    #     time.sleep(5)
    #     self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[1]/ul/li[4]/button").click()
    #     time.sleep(5)
    #
    #
    #     self.driver.find_element(By.XPATH, "//*[@id='loading-example']/div[1]/i[1]").click()
    #     time.sleep(5)
    #
    #     self.driver.find_element(By.XPATH, "//*[@id='loading-example']/div[2]/div/div/div[1]/div[1]/input").send_keys("Name")
    #     time.sleep(5)
    #     self.driver.find_element(By.XPATH, "//*[@id='ControlType']").send_keys("Text Area")
    #     time.sleep(5)
    #     # self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[1]/ul/li[4]/button").click()
    #     # time.sleep(5)
    #     # self.driver.find_element(By.XPATH,"//*[@id='loading-example']/div[1]/i[1]").click()
    #     # time.sleep(5)
    #     # self.driver.find_element(By.XPATH, "//*[@id='loading-example']/div[2]/div/div/div[1]/div[1]/input").send_keys("Address")
    #     # time.sleep(5)
    #     # self.driver.find_element(By.XPATH, "//*[@id='ControlType']").send_keys("Text Area")
    #     # time.sleep(5)
    #     self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
    #     time.sleep(20)
    #     # self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
    #     # time.sleep(10)
    #
    #     #self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[101]/td[7]/a[1]/i").click()
    #     self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[275]/td[7]/a[1]/i").click()
    #     time.sleep(5)
    #     self.driver.find_element(By.ID, "name").clear()
    #     time.sleep(10)
    #     self.driver.find_element(By.ID, "name").send_keys("updated form for Automation")
    #     time.sleep(10)
    #     self.driver.find_element(By.ID, "chkDataApproval").click()
    #     time.sleep(20)
    #     self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
    #     time.sleep(20)
    #     self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[275]/td[7]/a[3]/i").click()
    #     time.sleep(10)
    #     self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
    #     time.sleep(10)
    #     self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[275]/td[7]/a[4]/i").click()
    #     time.sleep(10)
    #     self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[3]/div/div/textarea").send_keys("Automation")
    #     time.sleep(10)
    #
    #     # self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[4]/button[1]").click()
    #     # time.sleep(10)
    #     self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
    #     time.sleep(5)
    #
    #
    #     # self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[108]/td[7]/a[5]/i").click()
    #     # time.sleep(5)
    #     # self.driver.find_element(By.ID, "UserForm").send_keys("Automation of Vericuda")
    #     # time.sleep(5)
    #     # self.driver.find_element(By.ID, "FolderToAssign").send_keys("vintee")
    #     # time.sleep(5)
    #     # self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/input").click()
    #     # time.sleep(5)
    #
    #
    #     # self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
    #     # time.sleep(5)
    #     self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[275]/td[7]/a[7]/i").click()
    #     time.sleep(5)
    #     self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
    #     time.sleep(5)
    #     self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[275]/td[7]/a[6]/i").click()
    #     time.sleep(5)
    #     self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
    #     time.sleep(5)
    #     self.driver.find_element(By.XPATH,"//*[@id='tree-table']/tbody/tr[275]/td[7]/a[2]/i").click()
    #     time.sleep(5)
    #     self.driver.find_element(By.XPATH,"/html/body/app/div/main/div/form/input").click()
    #     time.sleep(10)
    def test_observation(self):
        # Test name: vericoda2
        # Step # | name | target | value
        # 1 | open | https://qa.vericuda.net/account/login |
        self.driver.implicitly_wait(500)
        self.t = time.time()
        # self.driver.set_page_load_timeout(500)
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.get("https://qa.vericuda.net/account/login")
        # time.sleep(5)


        self.driver.set_page_load_timeout(400)
        print('Time consuming:', time.time() - self.t)

        # 2 | setWindowSize | 1050x664 |
        # self.driver.set_window_size(1050, 664)
        self.driver.maximize_window()
        # 3 | click | id=Username |
        self.driver.find_element(By.ID, "Username").click()
        time.sleep(10)
        # 4 | type | id=Username | shiva06051981@gmail.com
        self.driver.find_element(By.ID, "Username").send_keys("shiva06051981@gmail.com")
        # 5 | click | id=Password |
        self.driver.find_element(By.ID, "Password").click()
        time.sleep(5)
        # 6 | type | id=Password | 1
        self.driver.find_element(By.ID, "Password").send_keys("1")
        # 7 | click | css=.btn:nth-child(3) |
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/button").click()
        time.sleep(50)
        self.driver.find_element(By.XPATH,"/html/body/app/header/nav/div/div/ul/li[2]/a").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,"/html/body/app/div/main/div[1]/div/div[1]/button").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "area").send_keys("Area Site")
        time.sleep(5)
        self.driver.find_element(By.ID,"floor").send_keys("Floor1")
        time.sleep(5)
        self.driver.find_element(By.ID,"team").send_keys("Team1")
        time.sleep(5)

        self.driver.find_element(By.ID, "NonConformanceDetails").send_keys("details")
        time.sleep(5)

        self.driver.find_element(By.ID,"primary-cause").send_keys("Operations Issue")
        time.sleep(5)
        self.driver.find_element(By.ID,"CommonCause").send_keys("FD1")
        time.sleep(5)
        self.driver.find_element(By.ID,"Priority").send_keys("Minor")
        time.sleep(5)
        self.driver.find_element(By.ID,"MaintenanceNeeded").click()
        time.sleep(5)
        self.driver.find_element(By.NAME,"AreChecked").click()
        time.sleep(5)
        # self.driver.find_element(By.ID,"CorrectiveActionDate").send_keys("8-02-23")
        # time.sleep(5)
        # self.driver.find_element(By.ID,"TicketComments").send_keys("comments")
        # time.sleep(5)
        self.driver.find_element(By.XPATH,"/html/body/app/div/main/div/form/button[1]").click()
        time.sleep(10)

        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div[3]/table/tbody/tr[1]/td[3]/a/i").click()
        time.sleep(10)
        self.driver.find_element(By.ID, "CorrectiveActionTaken").send_keys("Action Token")
        time.sleep(15)
        self.driver.find_element(By.ID, "CorrectiveActionDate").send_keys("15-02-2023")
        time.sleep(15)

        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/button[1]").click()
        time.sleep(10)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div[3]/table/tbody/tr[1]/td[3]/a/i").click()
        time.sleep(10)

        self.driver.find_element(By.ID, "IsApproved").click()
        time.sleep(15)
        self.driver.find_element(By.ID, "IsHidden").click()
        time.sleep(15)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/button[1]").click()
        time.sleep(10)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div[1]/div/div[2]/button").click()
        time.sleep(10)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/div/div/table/tbody/tr[1]/td[1]/button").click()
        time.sleep(10)
        # self.driver.find_element(By.ID, "ChkShowClosed").click()
        # time.sleep(10)

    def test_event(self):
        # Test name: vericoda2
        # Step # | name | target | value
        # 1 | open | https://qa.vericuda.net/account/login |
        self.driver.implicitly_wait(500)
        self.t = time.time()
        # self.driver.set_page_load_timeout(500)
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.get("https://qa.vericuda.net/account/login")
        # time.sleep(5)
        self.driver.set_page_load_timeout(400)
        print('Time consuming:', time.time() - self.t)
        # 2 | setWindowSize | 1050x664 |
        # self.driver.set_window_size(1050, 664)
        self.driver.maximize_window()
        # 3 | click | id=Username |
        self.driver.find_element(By.ID, "Username").click()
        time.sleep(10)
        # 4 | type | id=Username | shiva06051981@gmail.com
        self.driver.find_element(By.ID, "Username").send_keys("shiva06051981@gmail.com")
        # 5 | click | id=Password |
        self.driver.find_element(By.ID, "Password").click()
        time.sleep(5)
        # 6 | type | id=Password | 1
        self.driver.find_element(By.ID, "Password").send_keys("1")
        # 7 | click | css=.btn:nth-child(3) |
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/button").click()
        time.sleep(50)

        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/div/aside/section[1]/ol/li/i").click()
        time.sleep(5)
        self.source = self.driver.find_element(By.XPATH, "//*[@id='tblParent']/tbody/tr[3]/td[1]")
        time.sleep(5)

        action = ActionChains(self.driver)
        # double click operation and perform
        action.double_click(self.source).perform()
        time.sleep(10)
        # to close the browser
        self.driver.find_element(By.ID, "EventFor").send_keys("Form")
        time.sleep(5)

        self.driver.find_element(By.ID, "EventForID").send_keys("Automation of Vericuda")
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='divModal']/div/div/div[5]/div[2]/input").clear()
        time.sleep(5)

        self.driver.find_element(By.XPATH, "//*[@id='divModal']/div/div/div[5]/div[2]/input").send_keys("Automation of Vericuda")
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='divModal']/div/div/div[6]/div[2]/textarea").clear()
        time.sleep(5)

        self.driver.find_element(By.XPATH, "//*[@id='divModal']/div/div/div[6]/div[2]/textarea").send_keys("Automation of Vericuda")
        time.sleep(5)

        self.driver.find_element(By.XPATH, "//*[@id='divModal']/div/div/div[7]/div[1]/div/table/tr[4]/td/input").click()
        time.sleep(5)
        self.driver.find_element(By.NAME, "AreChecked").click()
        time.sleep(5)
        self.driver.find_element(By.NAME, "VerificationFrequency").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='divModal']/div/div/div[8]/div[2]/button[1]").click()
        time.sleep(5)

    def test_capa(self):
         # Test name: vericoda2
         # Step # | name | target | value
         # 1 | open | https://qa.vericuda.net/account/login |
         self.driver.implicitly_wait(500)
         self.t = time.time()
         # self.driver.set_page_load_timeout(500)
         self.driver.get("chrome://settings/")
         self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
         self.driver.get("https://qa.vericuda.net/account/login")
         # time.sleep(5)

         self.driver.set_page_load_timeout(400)
         print('Time consuming:', time.time() - self.t)

         # 2 | setWindowSize | 1050x664 |
         # self.driver.set_window_size(1050, 664)
         self.driver.maximize_window()
         # 3 | click | id=Username |
         self.driver.find_element(By.ID, "Username").click()
         time.sleep(10)
         # 4 | type | id=Username | shiva06051981@gmail.com
         self.driver.find_element(By.ID, "Username").send_keys("shiva06051981@gmail.com")
         # 5 | click | id=Password |
         self.driver.find_element(By.ID, "Password").click()
         time.sleep(5)
         # 6 | type | id=Password | 1
         self.driver.find_element(By.ID, "Password").send_keys("1")
         # 7 | click | css=.btn:nth-child(3) |
         self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/button").click()
         time.sleep(50)
         self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[4]/a").click()
         time.sleep(5)
         self.driver.find_element(By.XPATH, "/html/body/app/div/main/div[1]/div[1]/div/button").click()
         time.sleep(5)
         self.driver.find_element(By.ID, "DateOfCapa").send_keys("01-03-2023")
         time.sleep(5)
         self.driver.find_element(By.ID, "RiskLevel").send_keys("Minor")
         time.sleep(5)
         self.driver.find_element(By.ID, "SummaryOfIssueType").send_keys("Foreign Material")
         time.sleep(5)
         self.driver.find_element(By.ID, "TypeOfCapa").send_keys("Quality")
         time.sleep(5)
         self.driver.find_element(By.ID, "Descriptionofissue").send_keys("Quality")
         time.sleep(5)
         self.driver.find_element(By.ID, "InitialissueCorrection").send_keys("Quality")
         time.sleep(5)
         self.driver.find_element(By.ID, "DateCorrected").send_keys("01-03-2023")
         time.sleep(5)
         self.driver.find_element(By.ID, "AssignedTo").send_keys("Pushpendra Rajput")
         time.sleep(5)
         self.driver.find_element(By.ID, "PersonwhoFixedIssue").send_keys("abc")
         time.sleep(5)
         self.driver.find_element(By.ID, "FishboneCause").send_keys("Material")
         time.sleep(5)
         self.driver.find_element(By.ID, "IsSpecificProblem").send_keys("Specific")
         time.sleep(5)
         self.driver.find_element(By.ID, "MeasurementNeeded").send_keys("measurement was in place")
         time.sleep(5)
         self.driver.find_element(By.ID, "WasFailureUnknown").send_keys("Previously Known")
         time.sleep(5)
         self.driver.find_element(By.ID, "SummaryOfRootCause").send_keys("Quality")
         time.sleep(5)
         self.driver.find_element(By.ID, "ProposedAction").send_keys("Maintenance")
         time.sleep(5)
         self.driver.find_element(By.ID, "PersonAssignedPreventiveAction").send_keys("Ashish Pal")
         time.sleep(5)
         self.driver.find_element(By.ID, "PreventiveActionDue").send_keys("03-03-2023")
         time.sleep(5)
         self.driver.find_element(By.ID, "PreventiveActionCompleted").send_keys("04-03-2023")
         time.sleep(5)
         self.driver.find_element(By.ID, "VerificationofPreventiveActionEffectiveness").send_keys("Verification")
         time.sleep(5)
         self.driver.find_element(By.ID, "DateEffectivenessAccepted").send_keys("04-03-2023")
         time.sleep(5)
         self.driver.find_element(By.ID, "WhoIsVerifying").send_keys("Test2")
         time.sleep(5)
         self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/div[13]/button").click()
         time.sleep(5)
         self.driver.find_element(By.XPATH,"/html/body/app/div/main/div[2]/div/div/table/thead/tr[3]/td[1]/a/i").click()
         time.sleep(5)
         self.driver.find_element(By.ID, "DateOfCapa").send_keys("05-03-23")
         time.sleep(5)
         # self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/div[14]/button[2]").click()
         # time.sleep(5)
         self.driver.find_element(By.XPATH,"/html/body/app/div/main/div/form/div[20]/button").click()
         time.sleep(5)
         # self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/div[14]/button[1]").click()
         # time.sleep(5)
         # self.driver.find_element(By.XPATH, "/html/body/app/div/main/div[1]/div[1]/div/a/i").click()
         # time.sleep(5)



if __name__ == "__main__":
    pytest.main()

# testClass = TestVericoda2()
# testClass.setup_method("")
# testClass.test_observation()
# testClass.test_capa()
# testClass.test_form()
# testClass.teardown_method()







