# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import random


class TestDepartment():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_department(self):
        # Test name: department
        # Step # | name | target | value
        # 1 | open | https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login |
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.get("https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login")
        # 2 | setWindowSize | 1050x664 |
        # self.driver.set_window_size(1050, 664)
        self.driver.maximize_window()
        self.driver.implicitly_wait(60)
        # self.driver.implicitly_wait(40)
        # 3 | click | css=#button-user-login > h3 |
        # self.driver.find_element(By.CSS_SELECTOR, "#button-user-login > h3").click()
        self.driver.find_element(By.XPATH, "//*[@id='button-user-login']/h3").click()
        time.sleep(10)

        # 4 | click | id=txtUsername |
        self.driver.find_element(By.ID, "txtUsername").click()
        time.sleep(5)
        # 5 | type | id=txtUsername | admin
        self.driver.find_element(By.ID, "txtUsername").send_keys("admin")
        # 6 | click | id=txtPassword |
        self.driver.find_element(By.ID, "txtPassword").click()
        time.sleep(5)
        # 7 | type | id=txtPassword | admin123
        self.driver.find_element(By.ID, "txtPassword").send_keys("admin123")
        # 8 | click | id=cmdLogin |
        self.driver.find_element(By.ID, "cmdLogin").click()
        time.sleep(5)
        # 9 | selectFrame | index=2 |
        # self.driver.switch_to.frame(2)

        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='IFRAMEcontent']")))

        time.sleep(10)
        # 10 | mouseOver | css=.rmItem:nth-child(10) > .rmRootLink > .rmText |
        element = self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/a/span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(30)
        # 11 | click | css=.rmExpanded > .rmText |
        # self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/div/div/div/ul/li[11]/a/span").click()
        # time.sleep(5)
        # self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/div/ul/li[19]/a/span").click()
        # time.sleep(5)
        # self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/div/div/div/ul/li[11]/a/span").click()
        # time.sleep(5)

        # self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/div/ul/li[19]/a/span").click()
        # time.sleep(5)

        self.driver.find_element(By.LINK_TEXT, "Department").click()
        time.sleep(5)

        # wait = WebDriverWait(self.driver, 10)
        # x = wait.until(EC.element_to_be_clickable((By.XPATH, "//*[@id='mainMenu']/ul/li[10]/div/div/div/ul/li[11]/a/span")))
        # time.sleep(5)
        # self.driver.execute_script("arguments[0].click();", x)

        self.driver.switch_to.frame("framepage")
        # # 15 | mouseDownAt | css=#DIVleft > div | 276,288.3333282470703
        self.driver.find_element(By.XPATH, "//*[@id='RPTsimpleItem_CtlGenericSelect_3_LBLSelectName_3']").click()
        time.sleep(10)

        self.driver.find_element(By.ID, "CtlConfigDepartment_LBTNaddNewRate").click()
        time.sleep(10)
        # # 26 | selectFrame | index=0 |
        self.driver.switch_to.frame(0)
        # WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.NAME, "framepage")))
        time.sleep(10)
        # # 27 | click | id=RDPchangeDate_popupButton |
        self.driver.find_element(By.ID, "RDPchangeDate_popupButton").click()
        time.sleep(5)
        # # 28 | click | linkText=13 |
        self.driver.find_element(By.LINK_TEXT, "13").click()
        time.sleep(5)
        # # 29 | type | name=RDPchangeDate | 2022/12/12
        # self.driver.find_element(By.NAME, "RDPchangeDate").send_keys("2022/12/12")
        # # 30 | click | id=TXTrate |
        self.driver.find_element(By.ID, "TXTrate").click()
        time.sleep(5)
        # # 31 | type | id=TXTrate | 7
        self.driver.find_element(By.ID, "TXTrate").send_keys("10")
        time.sleep(5)

        self.driver.find_element(By.ID, "TXTrateOT").click()
        time.sleep(5)
        # # 34 | type | id=TXTrateOT | 8
        self.driver.find_element(By.ID, "TXTrateOT").send_keys("10")
        time.sleep(5)

        self.driver.find_element(By.ID, "txtRate2").click()
        time.sleep(5)
        # # 37 | type | id=txtRate2 | 9
        self.driver.find_element(By.ID, "txtRate2").send_keys("10")
        time.sleep(5)
        self.driver.find_element(By.ID, "TXTrate2OT").click()
        time.sleep(5)
        # # 40 | type | id=TXTrate2OT | 5
        self.driver.find_element(By.ID, "TXTrate2OT").send_keys("10")
        time.sleep(5)

        self.driver.find_element(By.ID, "CMDupdate_input").click()
        time.sleep(5)
        # # 43 | click | id=CMDaccept_input |
        self.driver.find_element(By.ID, "CMDaccept_input").click()
        time.sleep(5)
        # # 44 | selectFrame | relative=parent |
        self.driver.switch_to.parent_frame()
        time.sleep(5)
        # self.driver.switch_to.frame("framepage")
        # time.sleep(20)
        self.driver.find_element(By.ID,"CtlConfigDepartment_RPTrateSchedule_CtlRateScheduleEdit_0_LBTNdeleteRequest_0").click()
        time.sleep(30)

        self.driver.find_element(By.ID, "CMDaddNew_input").click()
        time.sleep(5)
        # # 23 | click | id=CtlConfigDepartment_TXTname |
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTname").click()
        time.sleep(5)
        # # 24 | type | id=CtlConfigDepartment_TXTname | Auto
        # self.driver.find_element(By.ID, "CtlConfigDepartment_TXTname").send_keys("Auto")
        # # 25 | type | id=CtlConfigDepartment_TXTname | Auto
        random_string = ''
        for i in range(10):
            random_integer = random.randint(65, 90)
            # Keep appending random characters using chr(x)
            random_string += (chr(random_integer))
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTname").send_keys(random_string)
        # # 26 | click | id=CtlConfigDepartment_TXTnumber |
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTnumber").click()
        time.sleep(5)
        # # 27 | type | id=CtlConfigDepartment_TXTnumber | 1234
        # self.driver.find_element(By.ID, "CtlConfigDepartment_TXTnumber").send_keys("1234")
        # # 28 | type | id=CtlConfigDepartment_TXTnumber | 1234
        value = random.randint(1, 9)
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTnumber").send_keys(value)
        # # 29 | click | id=CtlConfigDepartment_TXTpbjcode |
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTpbjcode").click()
        time.sleep(5)
        # # 30 | type | id=CtlConfigDepartment_TXTpbjcode | 1234
        # self.driver.find_element(By.ID, "CtlConfigDepartment_TXTpbjcode").send_keys("1234")
        # # 31 | type | id=CtlConfigDepartment_TXTpbjcode | 1234
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTpbjcode").send_keys(value)
        # # 32 | click | id=CtlConfigDepartment_CBOdefaultSchedule_Input |
        # self.driver.find_element(By.ID, "CtlConfigDepartment_CBOdefaultSchedule_Input").click()
        # time.sleep(5)
        # # 33 | type | id=CtlConfigDepartment_CBOdefaultSchedule_Input | 7:30 AM - 5:00 PM
        self.driver.find_element(By.ID, "CtlConfigDepartment_CBOdefaultSchedule_Input").send_keys("7:30 AM - 5:00 PM")
        time.sleep(5)
        # # 34 | click | id=CtlConfigDepartment_TXTrate |
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTrate").click()
        time.sleep(5)
        # # 35 | type | id=CtlConfigDepartment_TXTrate | 1
        # self.driver.find_element(By.ID, "CtlConfigDepartment_TXTrate").send_keys("1")
        # # 36 | type | id=CtlConfigDepartment_TXTrate | 1
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTrate").send_keys("1")
        # # 37 | click | id=CtlConfigDepartment_TXTotRate |
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTotRate").click()
        time.sleep(5)
        # # 38 | type | id=CtlConfigDepartment_TXTotRate | 2
        # self.driver.find_element(By.ID, "CtlConfigDepartment_TXTotRate").send_keys("2")
        # # 39 | type | id=CtlConfigDepartment_TXTotRate | 2
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTotRate").send_keys("2")
        # # 40 | click | id=CtlConfigDepartment_TXTrate2 |
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTrate2").click()
        time.sleep(5)
        # # 41 | type | id=CtlConfigDepartment_TXTrate2 | 3
        # self.driver.find_element(By.ID, "CtlConfigDepartment_TXTrate2").send_keys("3")
        # # 42 | type | id=CtlConfigDepartment_TXTrate2 | 3
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTrate2").send_keys("3")
        # # 43 | click | id=CtlConfigDepartment_TXTotRate2 |
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTotRate2").click()
        time.sleep(5)
        # # 44 | type | id=CtlConfigDepartment_TXTotRate2 | 4
        # self.driver.find_element(By.ID, "CtlConfigDepartment_TXTotRate2").send_keys("4")
        # # 45 | type | id=CtlConfigDepartment_TXTotRate2 | 4
        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTotRate2").send_keys("4")
        # # 46 | click | id=CMDupdate_input |
        self.driver.find_element(By.ID, "CMDupdate_input").click()
        time.sleep(20)
        self.driver.find_element(By.ID, "RDPrecalculateDateFrom_popupButton").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "RDPrecalculateDateTo_popupButton").click()
        time.sleep(5)
        self.driver.find_element(By.CLASS_NAME, "rbDecorated").click()
        time.sleep(5)

        # wait = WebDriverWait(self.driver, 10)
        # x = wait.until(EC.element_to_be_clickable((By.ID, "RBTNrecalculateNow_input")))
        # time.sleep(5)
        # self.driver.execute_script("arguments[0].click();", x)

    def test_laborsetup(self):
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        # 1 | open | https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login |
        self.driver.get("https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login")
        # 2 | setWindowSize | 1024x664 |

        # self.driver.set_window_size(1024, 664)
        self.driver.maximize_window()
        self.driver.implicitly_wait(60)
        # 3 | click | css=#button-user-login > h3 |
        self.driver.find_element(By.CSS_SELECTOR, "#button-user-login > h3").click()
        time.sleep(5)
        # 4 | click | id=txtUsername |
        self.driver.find_element(By.ID, "txtUsername").click()
        time.sleep(5)
        # 5 | type | id=txtUsername | admin
        self.driver.find_element(By.ID, "txtUsername").send_keys("admin")
        # 6 | click | id=txtPassword |
        self.driver.find_element(By.ID, "txtPassword").click()
        time.sleep(5)
        # 7 | type | id=txtPassword | admin123
        self.driver.find_element(By.ID, "txtPassword").send_keys("admin123")
        # 8 | click | id=cmdLogin |
        self.driver.find_element(By.ID, "cmdLogin").click()
        time.sleep(5)
        # 9 | selectFrame | index=2 |
        # self.driver.switch_to.frame(2)

        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='IFRAMEcontent']")))

        time.sleep(10)
        # 10 | mouseOver | css=.rmItem:nth-child(10) > .rmRootLink > .rmText |
        element = self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/a/span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(30)

        # time.sleep(5)
        # # 10 | mouseOver | css=.rmItem:nth-child(10) > .rmRootLink > .rmText |
        # element = self.driver.find_element(By.CSS_SELECTOR, ".rmItem:nth-child(10) > .rmRootLink > .rmText")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        # time.sleep(5)
        # # 11 | click | css=.rmExpanded > .rmText |
        # self.driver.find_element(By.CSS_SELECTOR, ".rmExpanded > .rmText").click()
        # time.sleep(5)
        # # 12 | mouseOut | css=.rmExpanded > .rmText |
        # element = self.driver.find_element(By.CSS_SELECTOR, "body")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        # time.sleep(10)
        # # 13 | click | css=.rmScrollWrap .rmItem:nth-child(25) .rmText |
        # # self.driver.find_element(By.CSS_SELECTOR, ".rmScrollWrap .rmItem:nth-child(25) .rmText").click()
        # # time.sleep(10)

        self.driver.find_element(By.LINK_TEXT, "Labor Setup").click()
        time.sleep(10)

        # 14 | selectFrame | index=0 |
        # self.driver.switch_to.frame("framepage")
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.NAME, "framepage")))
        # 15 | click | id=RPTlaborSetup_CtlLaborSetup_0_LBLlevelName_0 |
        self.driver.find_element(By.ID, "RPTlaborSetup_CtlLaborSetup_0_LBLlevelName_0").click()
        time.sleep(5)
        # 16 | click | id=CMDcreateItem_input |
        self.driver.find_element(By.ID, "CMDcreateItem_input").click()
        time.sleep(5)
        # 17 | click | id=RptLaborCode_CtlLaborCode_0_TXTcode_0 |
        self.driver.find_element(By.ID, "RptLaborCode_CtlLaborCode_0_TXTcode_0").click()
        time.sleep(5)
        # 18 | type | id=RptLaborCode_CtlLaborCode_0_TXTcode_0 | Selenium
        self.driver.find_element(By.ID, "RptLaborCode_CtlLaborCode_0_TXTcode_0").send_keys("Selenium")
        # 19 | click | id=RptLaborCode_CtlLaborCode_0_TXTdescription_0 |
        self.driver.find_element(By.ID, "RptLaborCode_CtlLaborCode_0_TXTdescription_0").click()
        time.sleep(5)
        # 20 | type | id=RptLaborCode_CtlLaborCode_0_TXTdescription_0 | Selenium
        self.driver.find_element(By.ID, "RptLaborCode_CtlLaborCode_0_TXTdescription_0").send_keys("Selenium")
        time.sleep(5)
        # 21 | click | id=CMDupdate_input |
        self.driver.find_element(By.ID, "CMDupdate_input").click()
        time.sleep(5)

        self.driver.find_element(By.CSS_SELECTOR, "#RPTlaborSetup_CtlLaborSetup_0_DIVselect_0 td:nth-child(2)").click()
        time.sleep(5)
        # 16 | click | id=RptLaborCode_CtlLaborCode_8_TXTcode_8 |
        self.driver.find_element(By.ID, "RptLaborCode_CtlLaborCode_8_TXTcode_8").click()
        time.sleep(5)
        # 17 | click | css=#OPTitemsClosed > .rbText |
        self.driver.find_element(By.CSS_SELECTOR, "#OPTitemsClosed > .rbText").click()
        time.sleep(5)
        # 18 | click | id=CMDupdate_input |
        self.driver.find_element(By.ID, "CMDupdate_input").click()
        time.sleep(5)

    def test_timecard(self):
        # Test name: time_card
        # Step # | name | target | value
        # 1 | open | https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login |
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.get("https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login")
        self.driver.maximize_window()
        self.driver.implicitly_wait(60)

        # 2 | setWindowSize | 1936x1056 |
        # self.driver.set_window_size(1936, 1056)
        # 3 | click | css=#button-user-login > h3 |
        self.driver.find_element(By.CSS_SELECTOR, "#button-user-login > h3").click()
        # 4 | click | id=txtUsername |
        self.driver.find_element(By.ID, "txtUsername").click()
        # 5 | type | id=txtUsername | admin
        self.driver.find_element(By.ID, "txtUsername").send_keys("admin")
        # 6 | click | id=txtPassword |
        self.driver.find_element(By.ID, "txtPassword").click()
        # 7 | type | id=txtPassword | admin123
        self.driver.find_element(By.ID, "txtPassword").send_keys("admin123")
        # 8 | click | id=cmdLogin |
        self.driver.find_element(By.ID, "cmdLogin").click()
        # 9 | selectFrame | index=2 |
        # self.driver.switch_to.frame(2)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='IFRAMEcontent']")))

        time.sleep(10)
        # 10 | mouseOver | css=.rmItem:nth-child(7) > .rmRootLink > .rmText |
        self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[7]/a/span").click()
        time.sleep(5)
        # self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[7]/a/span").click()
        # time.sleep(5)
        # WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='mainMenu']/ul/li[7]/div/ul/li[24]/a/span")))
        self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[7]/div/ul/li[24]/a/span").click()
        time.sleep(5)

        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        # # 11 | click | css=.rmExpanded > .rmText |
        # self.driver.find_element(By.CSS_SELECTOR, ".rmExpanded > .rmText").click()
        # # 12 | mouseOut | css=.rmExpanded > .rmText |
        # element = self.driver.find_element(By.CSS_SELECTOR, "body")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element, 0, 0).perform()
        # # 13 | click | css=.rmItem:nth-child(7) .rmItem:nth-child(24) .rmText |
        # self.driver.find_element(By.CSS_SELECTOR, ".rmItem:nth-child(7) .rmItem:nth-child(24) .rmText").click()
        # # 14 | selectFrame | index=0 |
        self.driver.switch_to.frame(0)
        time.sleep(40)
        self.driver.find_element(By.ID, "ctl00_MainContent_cmbEmployees_Input").click()
        time.sleep(20)

        # # 15 | click | id=ctl00_body1 |
        # self.driver.find_element(By.ID, "ctl00_body1").click()
        # # 16 | click | id=ctl00_MainContent_cmbEmployees_Arrow |
        # self.driver.find_element(By.ID, "ctl00_MainContent_cmbEmployees_Arrow").click()
        # # 17 | click | css=.rcbHovered |
        # self.driver.find_element(By.CSS_SELECTOR, ".rcbHovered").click()
        # # 18 | type | id=ctl00_MainContent_cmbEmployees_Input | Singh, Amit
        self.driver.find_element(By.ID, "ctl00_MainContent_cmbEmployees_Input").send_keys("Singh, Amit")
        time.sleep(5)
        # # 19 | click | id=ctl00_MainContent_lnkPPPrev |
        self.driver.find_element(By.ID, "ctl00_MainContent_lnkPPPrev").click()
        time.sleep(20)
        self.driver.switch_to.parent_frame()

        self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[9]/a/span").click()
        time.sleep(10)
        self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[9]/div/ul/li[13]/a/span").click()
        time.sleep(10)
        # self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[9]/div/ul/li[13]/div/div/div/ul/li[54]/a/span").click()
        # time.sleep(50)

        wait = WebDriverWait(self.driver, 50)
        x = wait.until(EC.element_to_be_clickable((By.XPATH, "//*[@id='mainMenu']/ul/li[9]/div/ul/li[13]/div/div/div/ul/li[54]/a")))
        time.sleep(5)
        self.driver.execute_script("arguments[0].click();", x)
        time.sleep(20)
        self.driver.switch_to.frame("framepage")
        time.sleep(10)

        self.driver.find_element(By.ID, "IBTNrangeNext").click()
        time.sleep(10)

        self.driver.find_element(By.ID, "ChkAllEmployee").click()
        time.sleep(20)
        self.driver.find_element(By.XPATH, "//*[@id='i19']/label/input").click()
        time.sleep(15)
        self.driver.find_element(By.XPATH, "//*[@id='i20']/label/input").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,"//*[@id='ctl00_PNBmain_i0_i0_ContentPlaceHolder1_CMDreportBuild']/span").click()
        time.sleep(20)
        self.driver.switch_to.parent_frame()
        self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[1]/a/span").click()
        time.sleep(10)
        self.driver.switch_to.frame("framepage")
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='RTScontent']/div/ul/li[3]/span").click()
        time.sleep(10)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='RPVreportQueue']/iframe")))
        time.sleep(20)
        self.driver.find_element(By.ID, "RPTextendedInfo_CtlExtendedInfo_0_IBTNpreview_0").click()
        time.sleep(30)

    def test_copy_department(self):
        # Test name: department
        # Step # | name | target | value
        # 1 | open | https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login |
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.get("https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login")
        # 2 | setWindowSize | 1050x664 |
        # self.driver.set_window_size(1050, 664)
        self.driver.maximize_window()
        self.driver.implicitly_wait(60)
        # 3 | click | css=#button-user-login > h3 |
        self.driver.find_element(By.CSS_SELECTOR, "#button-user-login > h3").click()
        # 4 | click | id=txtUsername |
        self.driver.find_element(By.ID, "txtUsername").click()
        # 5 | type | id=txtUsername | admin
        self.driver.find_element(By.ID, "txtUsername").send_keys("admin")
        # 6 | click | id=txtPassword |
        self.driver.find_element(By.ID, "txtPassword").click()
        # 7 | type | id=txtPassword | admin123
        self.driver.find_element(By.ID, "txtPassword").send_keys("admin123")
        # 8 | click | id=cmdLogin |
        self.driver.find_element(By.ID, "cmdLogin").click()
        time.sleep(5)
        # 9 | selectFrame | index=2 |
        # self.driver.switch_to.frame(2)

        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='IFRAMEcontent']")))

        time.sleep(10)
        # 10 | mouseOver | css=.rmItem:nth-child(10) > .rmRootLink > .rmText |
        element = self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/a/span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(30)

        self.driver.find_element(By.LINK_TEXT, "Department").click()
        time.sleep(5)


        # 11 | click | css=.rmExpanded > .rmText |
        # self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/div/div/div/ul/li[11]/a/span").click()
        # time.sleep(5)

        self.driver.switch_to.frame("framepage")
        # # 15 | mouseDownAt | css=#DIVleft > div | 276,288.3333282470703
        self.driver.find_element(By.XPATH, "//*[@id='RPTsimpleItem_CtlGenericSelect_3_LBLSelectName_3']").click()
        time.sleep(20)

        self.driver.find_element(By.ID,"CMDaddCopy_input").click()
        time.sleep(10)

        value = random.randint(1, 5)

        self.driver.find_element(By.ID, "CtlConfigDepartment_TXTnumber").send_keys(value)
        time.sleep(10)

        self.driver.find_element(By.ID, "CMDupdate_input").click()
        time.sleep(10)

    def test_jobType(self):
        # Test name: Job_Type
        # Step # | name | target | value
        # 1 | open | https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx |
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.50)")
        self.driver.get("https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx")
        # 2 | setWindowSize | 1575x996 |
        # self.driver.set_window_size(1575, 996)
        self.driver.maximize_window()
        self.driver.implicitly_wait(60)
        # 3 | click | css=#button-user-login > h3 |
        self.driver.find_element(By.CSS_SELECTOR, "#button-user-login > h3").click()
        # 4 | click | id=txtUsername |
        self.driver.find_element(By.ID, "txtUsername").click()
        # 5 | type | id=txtUsername | admin
        self.driver.find_element(By.ID, "txtUsername").send_keys("admin")
        # 6 | click | id=txtPassword |
        self.driver.find_element(By.ID, "txtPassword").click()
        # 7 | type | id=txtPassword | admin123
        self.driver.find_element(By.ID, "txtPassword").send_keys("admin123")
        # 8 | click | id=cmdLogin |
        self.driver.find_element(By.ID, "cmdLogin").click()
        # 9 | selectFrame | index=2 |
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "// *[ @ id = 'IFRAMEcontent']")))

        time.sleep(10)
        # 10 | mouseOver | css=.rmItem:nth-child(10) > .rmRootLink > .rmText |
        element = self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/a/span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(30)
        # 11 | click | css=.rmExpanded > .rmText |
        # self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[10]/div/div/div/ul/li[23]/a/span").click()
        # time.sleep(5)

        self.driver.find_element(By.LINK_TEXT, "Job Type").click()
        time.sleep(20)

        # self.driver.switch_to.frame("framepage")
        # time.sleep(10)
        WebDriverWait(self.driver, 10).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='framepage']")))
        time.sleep(10)
        # # 15 | mouseDownAt | css=#DIVleft > div | 276,288.3333282470703
        # self.driver.find_element(By.XPATH, "//*[@id='RPTsimpleItem_CtlGenericSelect_3_LBLSelectName_3']").click()
        # time.sleep(10)
        # self.driver.find_element(By.ID, "RPTsimpleItem_CtlGenericSelect_0_LBLSelectName_0").click()
        # time.sleep(10)
        self.driver.find_element(By.ID, "CtlConfigJobType_LBTNaddNewRate").click()
        time.sleep(10)

        # wait = WebDriverWait(self.driver, 10)
        # x = wait.until(EC.element_to_be_clickable((By.ID, "CtlConfigJobType_LBTNaddNewRate")))
        # time.sleep(5)
        #
        # self.driver.execute_script("arguments[0].click();", x)
        # # # 26 | selectFrame | index=0 |
        # self.driver.switch_to.frame("RWgeneral")
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.NAME, "RWgeneral")))
        time.sleep(10)

        self.driver.find_element(By.ID, "RDPchangeDate_dateInput").send_keys("2022/12/12")
        time.sleep(5)
        # # # 30 | click | id=TXTrate |
        self.driver.find_element(By.ID, "TXTrate").click()
        time.sleep(5)
        # # # 31 | type | id=TXTrate | 7
        self.driver.find_element(By.ID, "TXTrate").send_keys("10")
        time.sleep(5)

        self.driver.find_element(By.ID, "TXTrateOT").click()
        time.sleep(5)
        # # # 34 | type | id=TXTrateOT | 8
        self.driver.find_element(By.ID, "TXTrateOT").send_keys("10")
        time.sleep(5)

        self.driver.find_element(By.ID, "txtRate2").click()
        time.sleep(5)
        # # # 37 | type | id=txtRate2 | 9
        self.driver.find_element(By.ID, "txtRate2").send_keys("10")
        time.sleep(5)
        self.driver.find_element(By.ID, "TXTrate2OT").click()
        time.sleep(5)
        # # # 40 | type | id=TXTrate2OT | 5
        self.driver.find_element(By.ID, "TXTrate2OT").send_keys("10")
        time.sleep(5)

        self.driver.find_element(By.ID, "CMDupdate_input").click()
        time.sleep(5)
        # # # 43 | click | id=CMDaccept_input |
        self.driver.find_element(By.ID, "CMDaccept_input").click()
        time.sleep(5)
        # # # 44 | selectFrame | relative=parent |
        self.driver.switch_to.parent_frame()
        time.sleep(5)
        # # self.driver.switch_to.frame("framepage")
        # # time.sleep(20)
        self.driver.find_element(By.ID,"CtlConfigJobType_RPTrateSchedule_CtlRateScheduleEdit_0_LBTNdeleteRequest_0").click()
        time.sleep(20)

        self.driver.find_element(By.ID, "CMDaddNew_input").click()
        time.sleep(5)
        # # # 23 | click | id=CtlConfigDepartment_TXTname |
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTname").click()
        time.sleep(5)
        random_string = ''
        for i in range(10):
            random_integer = random.randint(65, 90)
            # Keep appending random characters using chr(x)
            random_string += (chr(random_integer))
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTname").send_keys(random_string)
        # # # 26 | click | id=CtlConfigDepartment_TXTnumber |
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTnumber").click()
        time.sleep(5)

        # # # 27 | type | id=CtlConfigDepartment_TXTnumber | 1234
        # self.driver.find_element(By.ID, "CtlConfigJobType_TXTnumber").send_keys("1234")
        # # # 28 | type | id=CtlConfigDepartment_TXTnumber | 1234
        value = random.randint(1, 5)
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTnumber").send_keys(value)
        # # # 29 | click | id=CtlConfigDepartment_TXTpbjcode |
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTrate").click()
        time.sleep(5)
        # # # # 30 | type | id=CtlConfigDepartment_TXTpbjcode | 1234
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTrate").send_keys("1234")
        # # # # 31 | type | id=CtlConfigDepartment_TXTpbjcode | 1234
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTotRate").send_keys(value)
        # # # # 32 | click | id=CtlConfigDepartment_CBOdefaultSchedule_Input |
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTrate2").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTrate2").send_keys("3")
        # # # # 43 | click | id=CtlConfigDepartment_TXTotRate2 |
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTotRate2").click()
        time.sleep(5)
        # # # # 44 | type | id=CtlConfigDepartment_TXTotRate2 | 4
        # self.driver.find_element(By.ID, "CtlConfigDepartment_TXTotRate2").send_keys("4")
        # # # # 45 | type | id=CtlConfigDepartment_TXTotRate2 | 4
        self.driver.find_element(By.ID, "CtlConfigJobType_TXTotRate2").send_keys("4")
        # # # # 46 | click | id=CMDupdate_input |
        self.driver.find_element(By.ID, "CMDupdate_input").click()
        time.sleep(20)

        self.driver.find_element(By.ID, "RDPrecalculateDateFrom_popupButton").click()
        time.sleep(5)

        self.driver.find_element(By.ID, "RDPrecalculateDateTo_popupButton").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "RBTNrecalculateNow_input").click()
        time.sleep(5)

    def test_timeof_request(self):
        # Test name: test1
        # Step # | name | target | value
        # 1 | open | https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login |
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.get("https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login")
        # 2 | setWindowSize | 1050x664 |
        self.driver.maximize_window()
        self.driver.implicitly_wait(60)
        # self.driver.set_window_size(1050, 664)
        # 3 | click | css=#button-user-login > h3 |
        self.driver.find_element(By.CSS_SELECTOR, "#button-user-login > h3").click()
        time.sleep(5)
        # 4 | click | id=txtUsername |
        self.driver.find_element(By.ID, "txtUsername").click()
        time.sleep(5)
        # 5 | type | id=txtUsername | 0000609
        self.driver.find_element(By.ID, "txtUsername").send_keys("0000609")
        # 6 | click | id=txtPassword |
        self.driver.find_element(By.ID, "txtPassword").click()
        time.sleep(5)
        # 7 | type | id=txtPassword | 0000609
        self.driver.find_element(By.ID, "txtPassword").send_keys("0000609")
        # 8 | click | id=cmdLogin |
        self.driver.find_element(By.ID, "cmdLogin").click()
        time.sleep(5)
        # 9 | selectFrame | index=2 |
        # WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id="IFRAMEcontent"]")))
        self.driver.switch_to.frame(2)
        time.sleep(5)
        # 10 | mouseOver | css=.rmItem:nth-child(5) > .rmRootLink > .rmText |
        element = self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[5]/a/span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(20)
        # # 11 | mouseOut | css=.rmExpanded > .rmText |
        # element = self.driver.find_element(By.CSS_SELECTOR, "body")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        # time.sleep(5)
        # # 12 | click | css=.rmExpanded > .rmText |
        self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[5]/div/ul/li[15]/a/span").click()
        time.sleep(20)
        # # 13 | click | css=.rmItem:nth-child(15) .rmText |
        # self.driver.switch_to.frame("framepage")
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.NAME, "framepage")))
        time.sleep(5)
        self.driver.find_element(By.ID, "RPTemployee_LBLemployeeName_0").click()
        time.sleep(10)
        self.driver.find_element(By.ID, "DivAddNewRequest").click()
        time.sleep(20)
        self.driver.find_element(By.XPATH, "//*[@id='LBTNaddNewRequest']").click()
        time.sleep(20)

        self.driver.switch_to.frame(0)
        time.sleep(5)
        # # 24 | click | id=dtFrom_popupButton |
        # self.driver.find_element(By.ID, "dtFrom_popupButton").click()
        # time.sleep(5)
        # # 25 | click | linkText=15 |
        # self.driver.find_element(By.LINK_TEXT, "15").click()
        # time.sleep(5)
        # # 26 | pause | 50000 |
        #
        # # 27 | type | id=dtFrom_dateInput | 12/29/2022
        self.driver.find_element(By.ID, "dtFrom_dateInput").send_keys("01/13/2023")
        # # 28 | pause | 50000 |
        time.sleep(5)
        # # 29 | click | id=dtTo_popupButton |
        # self.driver.find_element(By.ID, "dtTo_popupButton").click()
        # time.sleep(5)
        # # 30 | click | linkText=15 |
        # self.driver.find_element(By.LINK_TEXT, "15").click()
        # time.sleep(5)
        # # 31 | type | id=dtTo_dateInput | 12/29/2022
        self.driver.find_element(By.ID, "dtTo_dateInput").send_keys("01/13/2023")
        time.sleep(5)
        # # 32 | click | id=txtHours |
        self.driver.find_element(By.ID, "txtHours").clear()
        time.sleep(5)
        # # 33 | type | id=txtHours | 8
        self.driver.find_element(By.ID, "txtHours").send_keys("8")
        time.sleep(10)
        # # 34 | click | id=cmbType_Input |
        # self.driver.find_element(By.ID, "cmbType_Input").click()
        # time.sleep(5)
        # # 35 | click | css=.rcbHovered |
        # self.driver.find_element(By.CSS_SELECTOR, ".rcbHovered").click()
        # time.sleep(5)
        # # 36 | type | id=cmbType_Input | PTO
        self.driver.find_element(By.ID, "cmbType_Input").send_keys("PTO")
        time.sleep(5)
        # # 37 | click | id=txtNote
        # self.driver.find_element(By.ID, "txtNote").click()
        # time.sleep(5)
        # # 38 | type | id=txtNote | Automation
        self.driver.find_element(By.ID, "txtNote").send_keys("Automation")
        time.sleep(5)
        # # 39 | click | id=CMDupdate_input |
        self.driver.find_element(By.ID, "CMDupdate_input").click()
        time.sleep(5)
        # # 40 | click | id=CMDaccept_input |
        self.driver.find_element(By.ID, "CMDaccept_input").click()
        time.sleep(5)

    # def test_timeofapproval(self):
    #     # Test name: time_of_approval
    #     # Step # | name | target | value
    #     self.driver.get("chrome://settings/")
    #     self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
    #
    #     # 1 | open | https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login |
    #     self.driver.get("https://ih20.acumenport.com/Inhouse/ProductBuild/Clockview/CHLogin.aspx?ApplicationSource=ClockView&Action=Login")
    #     # 2 | setWindowSize | 1050x664 |
    #     # self.driver.set_window_size(1050, 664)
    #     self.driver.maximize_window()
    #     # 3 | click | id=button-user-login |
    #     self.driver.find_element(By.ID, "button-user-login").click()
    #     time.sleep(5)
    #     # 4 | click | id=txtUsername |
    #     self.driver.find_element(By.ID, "txtUsername").click()
    #     time.sleep(5)
    #     # 5 | type | id=txtUsername | 000121
    #     self.driver.find_element(By.ID, "txtUsername").send_keys("000121")
    #     # 6 | click | id=txtPassword |
    #     self.driver.find_element(By.ID, "txtPassword").click()
    #     time.sleep(5)
    #     # 7 | type | id=txtPassword | 1234
    #     self.driver.find_element(By.ID, "txtPassword").send_keys("1234")
    #     # 8 | click | id=cmdLogin |
    #     self.driver.find_element(By.ID, "cmdLogin").click()
    #     time.sleep(5)
    #     # 9 | selectFrame | index=2 |
    #     self.driver.switch_to.frame(2)
    #     time.sleep(5)
    #     # 10 | mouseOver | css=.rmItem:nth-child(7) > .rmRootLink > .rmText |
    #     element = self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[7]/a/span")
    #     actions = ActionChains(self.driver)
    #     actions.move_to_element(element).perform()
    #     time.sleep(10)
    #     # 11 | click | css=.rmExpanded > .rmText |
    #     self.driver.find_element(By.XPATH, "//*[@id='mainMenu']/ul/li[7]/div/ul/li[26]/a/span").click()
    #     time.sleep(30)
    #     WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.NAME, "framepage")))
    #     time.sleep(5)
    #     self.driver.find_element(By.ID, "RPTemployee_DIVemployee_2").click()
    #     time.sleep(15)
    #     # self.driver.find_element(By.ID, "RPTrequestTimeOff_ctl34_CtlRequestTimeOff_CMDapprove_input").click()
    #     # time.sleep(5)



if __name__ == "__main__":
    pytest.main()

# t = TestDepartment()

# t.setup_method("")
# t.test_department()
# t.teardown_method("")
