# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options


class TestVericoda2():
    def setup_method(self, method):
        # self.driver = webdriver.Chrome()

        self.options = Options()
        self.options.headless = True
        self.options.add_experimental_option("excludeSwitches", ["enable-logging"])
        self.options.binary_location = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
        self.s = Service(r"C:\Users\mvintee\project_for_selenium\chromedriver.exe")
        self.driver = webdriver.Chrome(service=self.s)
        self.actions = ActionChains(self.driver)
        self.vars = {}


    def teardown_method(self, method):
        self.driver.quit()

    def test_form(self):
        # Test name: vericoda2
        # Step # | name | target | value
        # 1 | open | https://qa.vericuda.net/account/login |
        self.driver.implicitly_wait(500)
        self.t = time.time()
        # self.driver.set_page_load_timeout(500)
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.get("https://qa.vericuda.net/account/login")
        # time.sleep(5)
        self.driver.set_page_load_timeout(400)
        print('Time consuming:', time.time() - self.t)

        # 2 | setWindowSize | 1050x664 |
        # self.driver.set_window_size(1050, 664)
        self.driver.maximize_window()
        # 3 | click | id=Username |
        self.driver.find_element(By.ID, "Username").click()
        time.sleep(10)
        # 4 | type | id=Username | shiva06051981@gmail.com
        self.driver.find_element(By.ID, "Username").send_keys("shiva06051981@gmail.com")
        # 5 | click | id=Password |
        self.driver.find_element(By.ID, "Password").click()
        time.sleep(5)
        # 6 | type | id=Password | 1
        self.driver.find_element(By.ID, "Password").send_keys("1")
        # 7 | click | css=.btn:nth-child(3) |
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/button").click()
        time.sleep(50)
        self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
        time.sleep(5)
        # self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[21]/td[7]/a[1]/i").click()
        # time.sleep(10)
        # self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
        # time.sleep(10)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div[1]/div[1]/div/button[2]").click()
        time.sleep(10)
        self.driver.find_element(By.ID, "name").send_keys("Automation of Vericuda")
        time.sleep(5)
        self.driver.find_element(By.ID, "FormType").send_keys("Form")
        time.sleep(5)
        self.driver.find_element(By.ID, "Description").send_keys("Automation testing")
        time.sleep(5)

        self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[1]/div[1]/a[2]/div").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[1]/ul/li[4]/button").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='loading-example']/div[1]/i[1]").click()
        time.sleep(5)

        self.driver.find_element(By.XPATH, "//*[@id='loading-example']/div[2]/div/div/div[1]/div[1]/input").send_keys("Name")
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='ControlType']").send_keys("Text Area")
        time.sleep(5)
        # self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[1]/ul/li[4]/button").click()
        # time.sleep(5)
        # self.driver.find_element(By.XPATH,"//*[@id='loading-example']/div[1]/i[1]").click()
        # time.sleep(5)
        # self.driver.find_element(By.XPATH, "//*[@id='loading-example']/div[2]/div/div/div[1]/div[1]/input").send_keys("Address")
        # time.sleep(5)
        # self.driver.find_element(By.XPATH, "//*[@id='ControlType']").send_keys("Text Area")
        # time.sleep(5)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
        time.sleep(20)
        # self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
        # time.sleep(10)

        #self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[101]/td[7]/a[1]/i").click()
        self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[229]/td[7]/a[1]/i").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "name").clear()
        time.sleep(10)
        self.driver.find_element(By.ID, "name").send_keys("updated form for Automation")
        time.sleep(10)
        self.driver.find_element(By.ID, "chkDataApproval").click()
        time.sleep(20)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
        time.sleep(20)
        self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[229]/td[7]/a[3]/i").click()
        time.sleep(10)
        self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
        time.sleep(10)
        self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[229]/td[7]/a[4]/i").click()
        time.sleep(10)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[3]/div/div/textarea").send_keys("Automation")
        time.sleep(10)

        # self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[4]/button[1]").click()
        # time.sleep(10)
        self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
        time.sleep(5)


        # self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[108]/td[7]/a[5]/i").click()
        # time.sleep(5)
        # self.driver.find_element(By.ID, "UserForm").send_keys("Automation of Vericuda")
        # time.sleep(5)
        # self.driver.find_element(By.ID, "FolderToAssign").send_keys("vintee")
        # time.sleep(5)
        # self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/input").click()
        # time.sleep(5)


        # self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
        # time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[229]/td[7]/a[7]/i").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "/html/body/app/header/nav/div/div/ul/li[5]/a").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='tree-table']/tbody/tr[229]/td[7]/a[6]/i").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/form/div/div[2]/div[2]/button").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,"//*[@id='tree-table']/tbody/tr[229]/td[7]/a[2]/i").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,"/html/body/app/div/main/div/form/input").click()
        time.sleep(10)


    def test_observation(self):
        # Test name: vericoda2
        # Step # | name | target | value
        # 1 | open | https://qa.vericuda.net/account/login |
        self.driver.implicitly_wait(500)
        self.t = time.time()
        # self.driver.set_page_load_timeout(500)
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.get("https://qa.vericuda.net/account/login")
        # time.sleep(5)


        self.driver.set_page_load_timeout(400)
        print('Time consuming:', time.time() - self.t)

        # 2 | setWindowSize | 1050x664 |
        # self.driver.set_window_size(1050, 664)
        self.driver.maximize_window()
        # 3 | click | id=Username |
        self.driver.find_element(By.ID, "Username").click()
        time.sleep(10)
        # 4 | type | id=Username | shiva06051981@gmail.com
        self.driver.find_element(By.ID, "Username").send_keys("shiva06051981@gmail.com")
        # 5 | click | id=Password |
        self.driver.find_element(By.ID, "Password").click()
        time.sleep(5)
        # 6 | type | id=Password | 1
        self.driver.find_element(By.ID, "Password").send_keys("1")
        # 7 | click | css=.btn:nth-child(3) |
        self.driver.find_element(By.XPATH, "/html/body/app/div/main/div/form/button").click()
        time.sleep(50)
        self.driver.find_element(By.XPATH,"/html/body/app/header/nav/div/div/ul/li[2]/a").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,"/html/body/app/div/main/div[1]/div/div[1]/button").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "area").send_keys("Area Site")
        time.sleep(5)
        self.driver.find_element(By.ID,"floor").send_keys("Floor1")
        time.sleep(5)
        self.driver.find_element(By.ID,"team").send_keys("Team1")
        time.sleep(5)

        self.driver.find_element(By.ID, "NonConformanceDetails").send_keys("details")
        time.sleep(5)

        self.driver.find_element(By.ID,"primary-cause").send_keys("Operations Issue")
        time.sleep(5)
        self.driver.find_element(By.ID,"CommonCause").send_keys("FD1")
        time.sleep(5)
        self.driver.find_element(By.ID,"Priority").send_keys("Minor")
        time.sleep(5)
        self.driver.find_element(By.ID,"MaintenanceNeeded").click()
        time.sleep(5)
        self.driver.find_element(By.NAME,"AreChecked").click()
        time.sleep(5)
        # self.driver.find_element(By.ID,"CorrectiveActionDate").send_keys("8-02-23")
        # time.sleep(5)
        # self.driver.find_element(By.ID,"TicketComments").send_keys("comments")
        # time.sleep(5)
        # self.driver.find_element(By.XPATH,"/html/body/app/div/main/div/form/button[1]").click()
        # time.sleep(10)




if __name__ == "__main__":
    pytest.main()

# testClass = TestVericoda2()
# testClass.setup_method("")
# testClass.test_observation()
