import random
import time

import pytest
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait


class TestTest1():

    def setup_method(self, method):
        # self.driver = webdriver.Chrome()

        # self.options = Options()
        # self.options.headless = True
        # self.options.add_experimental_option("excludeSwitches", ["enable-logging"])
        #self.options.binary_location = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
        #self.s = Service(r"C:\Users\mvintee\project_for_selenium\chromedriver.exe")
        # self.driver = webdriver.Chrome(service=self.s)
        # self.actions = ActionChains(self.driver)
        # self.vars = {}
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        # Test name: login_logout
        # Step # | name | target | value
        # 1 | open | http://piswamp:81/vmis.in/ |
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.maximize_window()
        self.driver.get("http://192.168.20.60/NorthStarWMS/Dashboard/DashboardNew.aspx")
        # 2 | setWindowSize | 1280x680 |
        self.driver.find_element("id", "Login1_UserName").send_keys("wms")
        self.driver.find_element("id", "Login1_Password").send_keys("1")
        self.driver.find_element("class name", "rbText").click()

    def test_purchase_order(self):
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.maximize_window()
        self.driver.get("http://192.168.20.60/NorthStarWMS/Dashboard/DashboardNew.aspx")
        # 2 | setWindowSize | 1280x680 |
        self.driver.find_element("id", "Login1_UserName").send_keys("wms")
        self.driver.find_element("id", "Login1_Password").send_keys("1")
        self.driver.find_element("class name", "rbText").click()

        #def test_wms(self):
        #self.driver.get("http://192.168.20.60/NorthStarWMS/Dashboard/DashboardNew.aspx")
        element_to_hover_over = self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[2]/span/img')
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(3)
        self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[2]/div/ul/li[1]/a/img').click()
        time.sleep(1)
        self.driver.find_element("id", "ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl02_ctl00_btnAdd").click()
        time.sleep(5)
        self.driver.switch_to.frame("winPopup")
        time.sleep(5)
        self.driver.find_element("id", 'cmbVendor_Input').send_keys("TCS LTD")
        time.sleep(5)
        self.driver.find_element("id", 'cmbVendor_Input').click()
        time.sleep(5)
        self.driver.find_element("id", 'cmbVendor_Input').click()
        time.sleep(5)
        self.driver.find_element(By.ID, 'btnSave').click()
        time.sleep(5)
        self.driver.find_element(By.ID, 'ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl06_EditButton').click()
        time.sleep(5)
        self.driver.switch_to.frame("winPopup")
        time.sleep(5)
        self.driver.find_element(By.ID, 'cmbVendor_Input').clear()
        self.driver.find_element(By.NAME, 'cmbVendor').send_keys("MGUPTA")
        time.sleep(5)
        self.driver.find_element(By.ID, 'btnSave').click()
        time.sleep(5)
        self.driver.find_element(By.ID, 'ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl06_gbcDelete').click()
        time.sleep(5)
        self.driver.find_element(By.CLASS_NAME, "rwInnerSpan").click()
        time.sleep(5)
        self.driver.find_element(By.CLASS_NAME, "rwInnerSpan").click()
        time.sleep(5)
        self.driver.find_element(By.ID, 'ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl04_columnSelectCheckBox').click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,'//*[@id="ctl00_ContentPlaceHolder1_RadTabStrip"]/div/ul/li[2]/a/span/span/span').click()
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='ContentPlaceHolder1_DetailPage']/iframe")))
        time.sleep(5)
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_btnAdd").click()
        time.sleep(5)
        self.driver.switch_to.default_content()
        time.sleep(5)
        self.driver.switch_to.frame("winPopupChild")
        time.sleep(5)
        self.driver.find_element(By.ID, "cmbItem_Input").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='cmbItem_DropDown']/div[2]/ul/li[1]/table/tbody/tr/td[1]").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "txtOrderQty").send_keys(1)
        time.sleep(5)
        self.driver.find_element(By.ID, "cmbItemUOM_Input").send_keys('EACH [1]')
        time.sleep(5)
        self.driver.find_element(By.ID, "btnSave").click()
        time.sleep(5)
        self.driver.switch_to.default_content()
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='ContentPlaceHolder1_DetailPage']/iframe")))
        time.sleep(5)
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_cmbItem_Input").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,"//*[@id='PODetailGrid_ctl00_ctl02_ctl00_cmbItem_DropDown']/div[2]/ul/li[1]/table/tbody/tr/td[2]").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_txtOrderQty").send_keys(1)
        time.sleep(5)
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_txtOrderQty").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_btnQuickAdd").click()
        time.sleep(5)
        self.driver.switch_to.default_content()
        time.sleep(5)

    def test_inventory(self):
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.maximize_window()
        self.driver.get("http://192.168.20.60/NorthStarWMS/Dashboard/DashboardNew.aspx")
        # 2 | setWindowSize | 1280x680 |
        self.driver.find_element("id", "Login1_UserName").send_keys("wms")
        self.driver.find_element("id", "Login1_Password").send_keys("1")
        self.driver.find_element("class name", "rbText").click()

        element_to_hover_over = self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[3]/span/span')
        time.sleep(5)
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(5)
        self.driver.find_element(By.XPATH, '//*[@id="ctl00_MenuTabNew"]/ul/li[3]/div/ul/li[1]/a/span').click()
        time.sleep(5)
        self.driver.find_element(By.ID, 'ctl00_ContentPlaceHolder1_ItemGrid_ctl00_ctl02_ctl00_btnAdd').click()
        time.sleep(10)
        self.driver.switch_to.frame("winPopup")
        time.sleep(5)
        # wait.until(EC.element_to_be_clickable((By.ID, 'txtItemNumber'))).send_keys(input("enter the item no"))
        x = random.randint(98765, 99999)
        self.driver.find_element(By.ID, 'txtItemNumber').send_keys(x)
        time.sleep(5)
        self.driver.find_element(By.ID, "cmbCustOwner_Input").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='cmbCustOwner_DropDown']/div[1]/ul/li[1]").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "txtDescription").send_keys("new item")
        time.sleep(5)
        self.driver.find_element(By.ID, "btnSave_input").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "cmbCategory_Input").send_keys("01")
        time.sleep(5)
        self.driver.find_element(By.ID, "btnSave_input").click()
        time.sleep(20)
        self.driver.find_element(By.ID,"ctl00_ContentPlaceHolder1_ItemGrid_ctl00_ctl02_ctl03_FilterTextBox_ItemNo").send_keys(x)
        time.sleep(5)


    def test_pickpack(self):
        #self.driver.get("http://192.168.20.60/NorthStarWMS/Dashboard/DashboardNew.aspx")
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.maximize_window()
        self.driver.get("http://192.168.20.60/NorthStarWMS/Dashboard/DashboardNew.aspx")
        # 2 | setWindowSize | 1280x680 |
        self.driver.find_element("id", "Login1_UserName").send_keys("wms")
        self.driver.find_element("id", "Login1_Password").send_keys("1")
        self.driver.find_element("class name", "rbText").click()
        time.sleep(10)
        element_to_hover_over = self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[4]/span/span')
        time.sleep(5)
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(5)
        self.driver.find_element("xpath", "//*[@id='ctl00_MenuTabNew']/ul/li[4]/div/ul/li[11]/a/span").click()
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='ContentPlaceHolder1_PackOrder']/iframe")))
        time.sleep(5)
        self.driver.find_element("id", "modalPopup_C_btnSavePrintersetting").click()
        time.sleep(5)
        self.driver.find_element("id", "cmbOrder_Input").click()
        time.sleep(10)
        self.driver.find_element("id", "cmbOrder_i0_txtOrderNo").click()
        time.sleep(5)
        self.driver.find_element("id", "btnShipping_input").click()
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.NAME, "winShippingpopup")))
        time.sleep(5)
        self.driver.find_element("class name", "rwInnerSpan").click()
        time.sleep(5)
        self.driver.find_element("id", "cmbShippingProcess_Input").click()
        time.sleep(5)
        self.driver.find_element("xpath", "//*[@id='cmbShippingProcess_DropDown']/div/ul/li[2]").click()
        time.sleep(5)
        self.driver.find_element("id", "btnShip_input").click()
        time.sleep(5)
        self.driver.find_element("class name", "rwInnerSpan").click()
        time.sleep(5)
        self.driver.switch_to.default_content()
        time.sleep(5)
        self.driver.find_element("xpath","//*[@id='ctl00_ContentPlaceHolder1_RadTabStrip']/div/ul/li[9]/a/span/span/span").click()
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='ContentPlaceHolder1_SingleLine']/iframe")))
        self.driver.find_element("id", "modalPopup_C_btnSavePrintersetting").click()
        time.sleep(5)
        self.driver.find_element("id", "cmbCarrier_Input").send_keys("UPS")
        time.sleep(5)
        self.driver.find_element("id", "cmbMethod_Input").send_keys("Ground")
        time.sleep(5)
        self.driver.find_element("id", "txtMultiBoxCount").send_keys("1")
        time.sleep(5)
        self.driver.find_element("id", "txtWeight_InPounds").send_keys("1")
        time.sleep(5)
        self.driver.find_element("id", "txtScanItem").send_keys("Test01")
        time.sleep(5)
        self.driver.find_element("name", "btnShipOrder_input").click()
        time.sleep(5)
        self.driver.switch_to.default_content()
        time.sleep(5)
        self.driver.find_element("id", "btnLogout").click()
        time.sleep(10)

    def test_quick_pick(self):
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.maximize_window()
        self.driver.get("http://192.168.20.60/NorthStarWMS/User/PurchaseOrders.aspx?t=1&PO=1")
        # driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//s.png")
        self.driver.maximize_window()
        self.driver.implicitly_wait(20)
        print(self.driver.title)
        self.driver.find_element("id", "Login1_UserName").send_keys("wms")
        time.sleep(5)
        self.driver.find_element("id", "Login1_Password").send_keys("1")
        time.sleep(5)
        self.driver.find_element("class name", "rbText").click()
        time.sleep(5)
        element_to_hover_over = self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[4]/span/span')
        time.sleep(5)
        time.sleep(5)
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(5)
        self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[4]/div/ul/li[1]/a/span').click()
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("id","ctl00_ContentPlaceHolder1_ShipOrderGrid_ctl00_ctl04_columnSelectCheckBox").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("xpath","//*[@id='ctl00_ContentPlaceHolder1_RadTabStrip']/div/ul/li[2]/a/span/span/span").click()
        time.sleep(5)
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='ContentPlaceHolder1_SODetails']/iframe")))
        self.driver.find_element("id", "SoDetailGrid_ctl00_ctl04_SelectSelectCheckBox").click()
        time.sleep(5)
        time.sleep(5)
        element_to_hover_over = self.driver.find_element("id", "SoDetailGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_Input")
        time.sleep(5)
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(3)
        self.driver.find_element("xpath","//*[@id='SoDetailGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_DropDown']/div/ul/li[5]").click()
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.NAME, "winPopupRelease")))
        # driver.switch_to.frame("winPopupRelease")
        time.sleep(5)
        self.driver.find_element("id", "ManualAllocationGrid_ctl00_ctl04_txtAllocateQty_SpinUpButton").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("id", "btnAllocate_input").click()
        time.sleep(5)
        self.driver.find_element("id", "btnClose").click()
        time.sleep(5)

    def test_unsip(self):
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.maximize_window()
        self.driver.get("http://192.168.20.60/NorthStarWMS/User/PurchaseOrders.aspx?t=1&PO=1")
        # driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//s.png")
        self.driver.maximize_window()
        self.driver.implicitly_wait(20)
        print(self.driver.title)
        self.driver.find_element("id", "Login1_UserName").send_keys("wms")
        time.sleep(5)
        self.driver.find_element("id", "Login1_Password").send_keys("1")
        time.sleep(5)
        self.driver.find_element("class name", "rbText").click()
        time.sleep(5)
        element_to_hover_over = self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[4]/span/span')
        time.sleep(5)
        time.sleep(5)
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(5)
        self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[4]/div/ul/li[1]/a/span').click()
        time.sleep(5)
        self.driver.find_element("id","ctl00_ContentPlaceHolder1_ShipOrderGrid_ctl00_ctl04_columnSelectCheckBox").click()
        time.sleep(5)

        # WebDriverWait(driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH,"//*[@id='ContentPlaceHolder1_SOMaster']/iframe")))
        # time.sleep(5)
        self.driver.find_element("xpath","//*[@id='ctl00_ContentPlaceHolder1_RadTabStrip']/div/ul/li[1]/a/span/span/span").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("id","ctl00_ContentPlaceHolder1_ShipOrderGrid_ctl00_ctl04_columnSelectCheckBox").click()
        time.sleep(5)
        time.sleep(5)
        element_to_hover_over = self.driver.find_element("id","ctl00_ContentPlaceHolder1_ShipOrderGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_Input")
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(3)
        self.driver.find_element("xpath","//*[@id='ctl00_ContentPlaceHolder1_ShipOrderGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_DropDown']/div/ul/li[3]").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.switch_to.frame("winQuickPick")
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("id", "AutoAllocationGrid_ctl00_ctl04_columnSelectCheckBox").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("xpath", "//*[@id='rdbPack']/span[1]").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("id", "cmbStageLocation_Input").send_keys(100)
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("id", "btnAllocate_input").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("class name", "rwInnerSpan").click()
        time.sleep(5)
        time.sleep(5)
        # driver.switch_to.default_content()
        # time.sleep(5)
        # driver.find_element("class name","rtsTxt").click()
        # time.sleep(5)
        # driver.find_element("id","ctl00_ContentPlaceHolder1_ShipOrderGrid_ctl00_ctl16_columnSelectCheckBox").click()
        # time.sleep(10)
        self.driver.find_element("id", "btnClose").click()
        time.sleep(5)

    def test_unpick(self):
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.maximize_window()
        self.driver.get("http://192.168.20.60/NorthStarWMS/User/PurchaseOrders.aspx?t=1&PO=1")
        # driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//s.png")
        self.driver.maximize_window()
        self.driver.implicitly_wait(20)
        print(self.driver.title)
        self.driver.find_element("id", "Login1_UserName").send_keys("wms")
        time.sleep(5)
        self.driver.find_element("id", "Login1_Password").send_keys("1")
        time.sleep(5)
        self.driver.find_element("class name", "rbText").click()
        time.sleep(5)
        element_to_hover_over = self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[4]/span/span')
        time.sleep(5)
        time.sleep(5)
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(5)
        self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[4]/div/ul/li[1]/a/span').click()
        time.sleep(5)

        self.driver.find_element("id","ctl00_ContentPlaceHolder1_ShipOrderGrid_ctl00_ctl04_columnSelectCheckBox").click()
        time.sleep(5)
        time.sleep(5)
        element_to_hover_over = self.driver.find_element("id","ctl00_ContentPlaceHolder1_ShipOrderGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_Input")
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(5)
        self.driver.find_element("xpath","//*[@id='ctl00_ContentPlaceHolder1_ShipOrderGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_DropDown']/div/ul/li[2]").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.switch_to.frame("winQuickPick")
        time.sleep(5)
        self.driver.find_element("id", "gridUnPick_ctl00_ctl06_Detail10_ctl02_ctl00_columnSelectCheckBox").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element("id", "btnUnPick_input").click()
        time.sleep(5)
        time.sleep(5)
        self.driver.find_element(By.CLASS_NAME, "rwInnerSpan").click()
        time.sleep(5)
        time.sleep(5)
        # self.driver.find_element(By.ID, "btnClose_input").click()
        # time.sleep(10)

    def test_final_receiving(self):
        self.driver.get("chrome://settings/")
        self.driver.execute_script("chrome.settingsPrivate.setDefaultZoom(.67)")
        self.driver.maximize_window()
        self.driver.implicitly_wait(20)
        self.driver.get("http://192.168.20.60/NorthStarWMS/login.aspx?ReturnUrl=%2fNorthStarWMS%2fDashboard%2fDashboardNew.aspx")
        #self.driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//screenshott.png")
        self.driver.maximize_window()
        self.driver.implicitly_wait(5)

        time.sleep(3)
        print(self.driver.title)
        wait = WebDriverWait(self.driver, 5)

        self.driver.find_element("id", "Login1_UserName").send_keys("wms")
        self.driver.find_element("id", "Login1_Password").send_keys("1")

        self.driver.find_element("class name", "rbText").click()

        element_to_hover_over = self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[2]/span/img')

        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(3)
        #self.driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//screenshott.png")

        self.driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[2]/div/ul/li[1]/a/img').click()
        time.sleep(1)

        self.driver.find_element("id", "ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl02_ctl00_btnAdd").click()

        time.sleep(5)
        self.driver.switch_to.frame("winPopup")
        time.sleep(5)
        #self.driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//screenshott.png")
        # driver.switch_to.window(driver.current_window_handle)
        # driver.execute_script("window.focus();")
        # time.sleep(5)
        time.sleep(20)
        self.driver.find_element("id", 'cmbVendor_Input').send_keys("TCS LTD")
        time.sleep(5)
        self.driver.find_element("id", 'cmbVendor_Input').click()
        time.sleep(5)
        self.driver.find_element("id", 'cmbVendor_Input').click()
        time.sleep(5)
        self.driver.find_element(By.ID, 'btnSave').click()
        # x=wait.until(EC.element_to_be_clickable((By.ID, 'btnSave')))
        time.sleep(5)
        #self.driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//screenshott.png")
        # driver.execute_script("arguments[0].click();", x)
        time.sleep(5)
        self.driver.find_element(By.ID, 'ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl06_EditButton').click()
        time.sleep(5)
        self.driver.switch_to.frame("winPopup")
        time.sleep(5)
        #driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//screenshott.png")
        self.driver.find_element(By.ID, 'cmbVendor_Input').clear()

        self.driver.find_element(By.NAME, 'cmbVendor').send_keys("MGUPTA")
        time.sleep(5)
        self.driver.find_element(By.ID, 'btnSave').click()
        time.sleep(5)
        #self.driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//screenshott.png")
        self.driver.find_element(By.ID, 'ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl06_gbcDelete').click()
        time.sleep(5)
        # driver.switch_to.default_content()
        # obj = driver.switch_to.alert
        # obj.accept()
        # WebDriverWait(driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.NAME,".rwWindowContent")))
        # time.sleep(5)
        self.driver.find_element(By.CLASS_NAME, "rwInnerSpan").click()
        time.sleep(5)
        #self.driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//screenshott.png")
        self.driver.find_element(By.CLASS_NAME, "rwInnerSpan").click()
        #self.driver.save_screenshot("c://Users//mvintee//project_for_selenium//screenshotinfo//screenshott.png")
        time.sleep(10)
        # driver.find_element("xpath", '//*[@id="ctl00_MenuTabNew"]/ul/li[2]/div/ul/li[1]/a/img').click()
        # time.sleep(1)
        self.driver.find_element("id", 'ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl04_columnSelectCheckBox').click()
        time.sleep(5)
        self.driver.find_element("xpath",'//*[@id="ctl00_ContentPlaceHolder1_RadTabStrip"]/div/ul/li[2]/a/span/span/span').click()
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='ContentPlaceHolder1_DetailPage']/iframe")))
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_btnAdd").click()
        time.sleep(5)
        self.driver.switch_to.default_content()
        time.sleep(5)
        self.driver.switch_to.frame("winPopupChild")
        time.sleep(5)
        self.driver.find_element(By.ID, "cmbItem_Input").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id='cmbItem_DropDown']/div[2]/ul/li[1]/table/tbody/tr/td[1]").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "txtOrderQty").send_keys(1)
        time.sleep(5)
        self.driver.find_element(By.ID, "cmbItemUOM_Input").send_keys('EACH [1]')
        time.sleep(5)
        self.driver.find_element(By.ID, "btnSave").click()
        time.sleep(5)
        self.driver.switch_to.default_content()
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, "//*[@id='ContentPlaceHolder1_DetailPage']/iframe")))
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_cmbItem_Input").click()
        self.driver.find_element(By.XPATH,"//*[@id='PODetailGrid_ctl00_ctl02_ctl00_cmbItem_DropDown']/div[2]/ul/li[1]/table/tbody/tr/td[2]").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_txtOrderQty").send_keys(1)
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_txtOrderQty").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "PODetailGrid_ctl00_ctl02_ctl00_btnQuickAdd").click()
        time.sleep(5)

        # Additional
        # driver.find_element("id","PODetailGrid_ctl00_ctl04_SelectSelectCheckBox").click()
        # time.sleep()
        element_to_hover_over = self.driver.find_element("id", "PODetailGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_Input")
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(3)
        self.driver.find_element("xpath","//*[@id='PODetailGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_DropDown']/div/ul/li[5]").click()
        time.sleep(5)
        WebDriverWait(self.driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.NAME, "winReceiveManually")))
        # driver.switch_to.frame("winReceiveManually")
        time.sleep(5)
        self.driver.find_element("id", "cmbItem_Arrow").click()
        time.sleep(5)
        self.driver.find_element("id", "cmbItem_Input").send_keys(92606)
        time.sleep(5)
        self.driver.find_element("id", "cmbItem_Input").click()
        time.sleep(5)
        self.driver.find_element("id", "cmbLocationBin_Input").clear()
        time.sleep(5)
        self.driver.find_element("id", "cmbLocationBin_Input").send_keys(100)
        time.sleep(5)
        self.driver.find_element("id", "cmbLocationBin_Input").click()
        time.sleep(5)
        self.driver.find_element("id", "btnSave_input").click()
        time.sleep(5)
        self.driver.switch_to.default_content()
        # time.sleep(5)
        # driver.switch_to.frame("RadTabStrip")
        time.sleep(5)
        self.driver.find_element("class name", "rtsTxt").click()
        time.sleep(5)
        self.driver.find_element("id", "ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl04_columnSelectCheckBox").click()
        time.sleep(5)
        element_to_hover_over = self.driver.find_element("id","ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_Input")
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        time.sleep(3)
        self.driver.find_element("xpath","//*[@id='ctl00_ContentPlaceHolder1_POGrid_ctl00_ctl02_ctl00_cmbSOFilterOption_DropDown']/div/ul/li[5]").click()
        time.sleep(5)
        WebDriverWait(self.driver, 50).until(EC.frame_to_be_available_and_switch_to_it((By.NAME, "winPopup")))
        #self.driver.switch_to.frame("winPopup")
        time.sleep(10)
        x = self.driver.find_element("id", "cmbLocationBin_Input")
        x.clear()
        time.sleep(5)
        self.driver.find_element("id", "cmbLocationBin_Input").send_keys("100")
        time.sleep(5)
        self.driver.find_element("id", "cmbLocationBin_Arrow").click()
        time.sleep(5)
        self.driver.find_element("id", "btnReceive_input").click()
        time.sleep(10)


if __name__=="__main__":
    pytest.main()

# t = TestTest1()
# t.setup_method("")
# t.test_login()
# #t.test_quick_pick()
# # t.test_pickpack()
# # t.test_manual_pick()
# # t.test_final_receiving()
# #t.teardown_method("")


